#!/bin/sh

set -e

echo '+cargo test'
cargo test
echo '+cargo clippy -- -D warnings'
cargo clippy -- -D warnings
echo '+cargo fmt -- --check'
cargo fmt -- --check
echo '+cargo audit'
cargo audit
echo '+npm run --silent test:e2e'
npm run --silent test:e2e
