name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: "1.89.0"
        components: rustfmt, clippy
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Install cargo-audit
      run: cargo install cargo-audit
    
    - name: Run tests
      run: |
        echo '+cargo test'
        cargo test
    
    - name: Run clippy
      run: |
        echo '+cargo clippy -- -D warnings'
        cargo clippy -- -D warnings
    
    - name: Check formatting
      run: |
        echo '+cargo fmt -- --check'
        cargo fmt -- --check
    
    - name: Run security audit
      run: |
        echo '+cargo audit'
        cargo audit
